### ISSUE TITLE
nginx waf

### ISSUE THREAD

**Issue by arun81** [ppabc/nginx-waf#1]
Hi 

The project looks promising 
When I have started using this Dockerfile , I am getting page cannot be displayed in the container .
After I have changed / made  the following setting things are working fine  . I would also request you to please also  change the things below :- 

I request you please shift the two files ( nginx.conf & nginx.vh.default.conf ) in nginx-waf/nginx/stable/  folder from root/etc/nginx folder  and also make changes in Dockerfile below to get it working 
===============================================
# Copy nginx configuration files
COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.vh.default.conf /etc/nginx/conf.d/default.conf

ADD root /
================================================

Now Everything is working fine in Nginx-Stable and same way for Beta/Mainline

Thanks

**Comment by ppabc** [comment]
Use this file to create a image

/nginx/mainline/Dockerfile

Start command

Docker run-d -- name nginx1-v/data:/data -- net = host-it ppabc/nginx-waf: mainline
